workflows:
  android-release:
    name: Gossip Android Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - VAR
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm install -g pnpm
          pnpm install
      - name: Expo Prebuild
        script: |
          npx expo prebuild --platform android
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      - name: Build Android Release APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - ${CM_EMAIL}
